### ISSUE TITLE
gmail_safe crashes due to too many open file handles

### ISSUE THREAD

**Issue by jbfink** [eblume/gmail_safe#4]
When running gmail_safe, I will get the occasional crash with the following output: 

{ [Error: EMFILE, open '/home/jbfink/gmail2/.meta/lastid.txt']
  errno: 20,
  code: 'EMFILE',
  path: '/home/jbfink/gmail2/.meta/lastid.txt' }

Restarting gmail_safe works and it carries on as usual for a time before crashing again with the same message. I have a pretty big inbox and I'm using an application password, but I'm not sure if that matters.

**Comment by tigroumeow** [comment]
Hello :) Did you re-submit the last version to NPM? Just curious. Thanks :)

**Comment by eblume** [comment]
I did not and have no intention of doing so any time soon, this project is pretty much abandoned. Feel free to take over for me if you would like to, though you'll have to figure out how.

**Comment by tigroumeow** [comment]
Understood! I was just looking for a quick and simple way to backup my gmail and a node-based solution would have been best. Yours is the only one. Oh, well... :) Thanks for the update :)

**Comment by eblume** [comment]
Thanks for letting me know, that's really too bad! I might have to code this up again in another language. I made this project in a weekend to learn javascript - it was a good learning experience but I'm not fond of the language.
